### ISSUE TITLE
Оформить диаграмму пакетов UML для своего продукта

### ISSUE THREAD

**Issue by babkaAnna** [babkaAnna/friend-or-foe#11]

**Comment by Semyon2807** [comment]
Диаграмма пакетов для продукта "Свой-Чужой" готова!

**Comment by babkaAnna** [comment]
А шо, а где смотреть?

**Comment by Semyon2807** [comment]
в следующей задаче, куда надо скидывать файлы (прикрепил папку)

**Comment by babkaAnna** [comment]
А, всё, поняла
Молодец, 5!

**Comment by Semyon2807** [comment]
[диаграмма.pdf](https://github.com/babkaAnna/friend-or-foe/files/13769538/default.pdf)

**Comment by Semyon2807** [comment]
[диаграмма (1).pdf](https://github.com/babkaAnna/friend-or-foe/files/13877989/1.pdf)

**Comment by Semyon2807** [comment]
По диаграмме пактов мы можем пронаблюдать зависимость пакетов в нашей программе. В нашем случае основной пакет CV2 (библиотека с машиной) зависит от таких сущностей как frontalface и eye. Вспомогательный независимый пакет pyttsx3, используемый для озвучки. И пакет OS, помогающий в координации по фотографиям, зависит от одноименного пакета picture.

**Comment by Semyon2807** [comment]
![image](https://github.com/babkaAnna/friend-or-foe/assets/149473578/a090c638-1d3c-47a6-9092-b012086732af)

**Comment by Semyon2807** [comment]
У пользователя имеется 3 выбора, который каждый ведет к использованию библиотеки CV2 распознаванию лица, с возможностью реализации фото или видео.

**Comment by Semyon2807** [comment]
![image](https://github.com/babkaAnna/friend-or-foe/assets/149473578/f08ef1c3-01f9-4b6a-b7a6-856ea342bb12)

**Comment by Semyon2807** [comment]
У пользователя имеется 3 выбора, который каждый ведет к использованию библиотеки CV2, зависящее от таких сущностей как frontalface и eye, распознавание лица, с возможностью реализации фото или видео.
