### ISSUE TITLE
Подготовить материалы для включения в ПЗ

### ISSUE THREAD

**Issue by babkaAnna** [babkaAnna/friend-or-foe#13]
1. Код – в приложение А
2. Диаграммы

**Comment by Semyon2807** [comment]
[курсач.zip](https://github.com/babkaAnna/friend-or-foe/files/13705719/default.zip)



В папке лежат 2 файла: код и диаграмма, а также 2 папки с реальными фотографиями и базовые изображения для работы программы.

**Comment by babkaAnna** [comment]
Просто супер!
Молодец, закрываю задачу!

**Comment by Semyon2807** [comment]
![image](https://github.com/babkaAnna/friend-or-foe/assets/149473578/42256218-ca2b-46a2-b7b6-5864e63f3137)
![image](https://github.com/babkaAnna/friend-or-foe/assets/149473578/dd353b11-ad73-42e6-a55d-67f938ab695f)
![image](https://github.com/babkaAnna/friend-or-foe/assets/149473578/79742140-2f8a-4c37-85ca-43d3e2e0b051)
![image](https://github.com/babkaAnna/friend-or-foe/assets/149473578/f4127ecf-9e22-41aa-abf3-53911c8bebe9)


работа с фотографией

**Comment by Semyon2807** [comment]
![image](https://github.com/babkaAnna/friend-or-foe/assets/149473578/0e84fee5-23b9-4897-963d-36d045a00f02)
![image](https://github.com/babkaAnna/friend-or-foe/assets/149473578/77bd5f7b-97b5-4277-a19d-b2549f185f1a)

работа с видео

**Comment by Semyon2807** [comment]
![image](https://github.com/babkaAnna/friend-or-foe/assets/149473578/e7a1601d-3e2b-4314-8658-fb49085d7474)

неправильный ввод пользователя

**Comment by Semyon2807** [comment]
[код.zip](https://github.com/babkaAnna/friend-or-foe/files/13877695/default.zip)
обновленный код, обновляйте диаграммы

**Comment by Semyon2807** [comment]
добавил возможность остановки слайда фото
