### ISSUE TITLE
Придумать и обосновать архитектуру продукта

### ISSUE THREAD

**Issue by babkaAnna** [babkaAnna/friend-or-foe#15]

**Comment by tv1go** [comment]
1. Источники изображений:

- Веб-камеры
- Файлы изображений

2. Модуль обнаружения лиц:

- Использует алгоритмы машинного обучения (OpenCV)
- Обеспечивает высокую точность и адаптируемость к различным условиям освещения и углам обзора

3. Модуль различения своих и чужих:

- Включает обученные классификаторы для отличия человеческих лиц от других объектов
- Поддерживает обновление и обучение классификаторов для повышения эффективности

4. Интерфейс пользователя:

- Визуализирует обнаруженные лица на экране
- Оповещает операторов о событиях, таких как обнаружение "чужих" лиц

5. Хранение данных:

- Сохраняет метаданные о событиях обнаружения для последующего анализа
- Ведет историю обнаруженных лиц для улучшения системы в будущем

**Обоснование архитектуры**

1. Использование OpenCV: 

- Алгоритмы машинного обучения в OpenCV обеспечивают отличную производительность при обнаружении лиц и поддерживают различные входные источники изображений.

2. Обученные классификаторы: 

- Для эффективного отделения человеческих лиц от прочих объектов важно использовать обученные классификаторы, что повышает точность системы.

3. Интерфейс пользователя: 

- Визуализация и оповещения делают продукт более пользовательским, обеспечивая операторам наглядное представление обнаруженных лиц и моментальное реагирование на важные события.
