### ISSUE TITLE
Написать требования к системному ПО (ОС, СУБД) 

### ISSUE THREAD

**Issue by babkaAnna** [babkaAnna/friend-or-foe#16]

**Comment by tv1go** [comment]
Минимальные требования:
Процессор:
Не слишком старый. Будет лучше, если имеется двухъядерный процессор.

Память:
4 ГБ минимум.

Видеокарта:
Потребуется видеокарта, которая поддерживает графический стандарт OpenGL 2.0 или выше.

Жесткий диск:
Не менее 10ГБ свободного места.

Операционная система:
Windows 10 (предпочтительно 64-бит), Linux или macOS 10.14 и более.


Рекомендованные настройки

Процессор:
4-х ядерный процессор.

Память:
8ГБ оперативки.

Видеокарта:
Дискретная видеокарта с поддержкой CUDA.

Жесткий диск:
20ГБ для идеала.

Операционная система:
Последняя версия винды, линукса либо мак ОС

Дополнительно:
OpenCV с поддержкой GPU для улучшения производительности
