### ISSUE TITLE
Архитектурная диаграмма 

### ISSUE THREAD

**Issue by babkaAnna** [babkaAnna/friend-or-foe#17]
What is Architecture Diagramming? - Software & System Architecture Diagramming Explained - AWS (amazon.com))

**Comment by tv1go** [comment]
![image](https://github.com/babkaAnna/friend-or-foe/assets/134600713/f1afa314-1b0c-4547-beba-303c044a74b9)

Код:
@startuml

class Пользователь
class РоботСвойЧужой {
  + обнаружитьЛицо(фотографию)
}
class АлгоритмОбнаруженияЛиц {
  + обнаружитьЛицо(фотографию)
  + обработать(фотографию)
}
class Изображение {
  + данные
}
class ДвижокГолоса {
  + воспроизвести
}

Пользователь --> РоботСвойЧужой : обнаружитьЛицо(фотографию)
РоботСвойЧужой --> АлгоритмОбнаруженияЛиц : обнаружитьЛицо(фотографию)
АлгоритмОбнаруженияЛиц --> Изображение : обработать(фотографию)
АлгоритмОбнаруженияЛиц --> ДвижокГолоса : воспроизвести

@enduml

**Comment by tv1go** [comment]
![image](https://github.com/babkaAnna/friend-or-foe/assets/134600713/d5a15cf0-c397-45b3-8a13-bf719432ac29)
Обновленная архитектурная диаграмма

**Comment by tv1go** [comment]
![image](https://github.com/babkaAnna/friend-or-foe/assets/134600713/ec76780c-238d-472d-bdd2-228c0d3c2e9a)
ФИНАЛ0ЧКА ДИАГРАММЫ!!! УСПЕХ!!!
