### ISSUE TITLE
Функциональная диаграмма UML

### ISSUE THREAD

**Issue by babkaAnna** [babkaAnna/friend-or-foe#18]

**Comment by tv1go** [comment]
![image](https://github.com/babkaAnna/friend-or-foe/assets/134600713/c57d3cf8-6b08-4069-9be4-80717c79c6c8)
Код:
@startuml

actor Пользователь
participant "РоботСвойЧужой" as Robot
database "База Данных" as Database
database "Голосовой Движок" as VoiceEngine

Пользователь -> Robot: Запрос обнаружения лиц
activate Robot
Robot -> Database: Загрузка фотографии
activate Database
Database --> Robot: Фотография
deactivate Database
Robot -> Robot: Обработка фотографии
Robot -> VoiceEngine: Воспроизведение
deactivate Robot
deactivate VoiceEngine

@enduml

**Comment by tv1go** [comment]
![Функциональная диаграмма КУРСАЧ](https://github.com/babkaAnna/friend-or-foe/assets/134600713/1ead2b8f-4f4a-49ad-aa25-d97c9217044e)
Обновленная диаграмма

**Comment by tv1go** [comment]
![image](https://github.com/babkaAnna/friend-or-foe/assets/134600713/f0396789-0c92-44d0-8344-ba9beec92d69)
Финальный результат
