### ISSUE TITLE
Диаграмма последовательности UML 

### ISSUE THREAD

**Issue by babkaAnna** [babkaAnna/friend-or-foe#19]
(для одной выбранной ключевой функции)

**Comment by tv1go** [comment]
![image](https://github.com/babkaAnna/friend-or-foe/assets/134600713/1da2e7b7-127d-46d5-9dd4-bf02a3ffde7b)

**Comment by tv1go** [comment]
![Диаграмма последовательности КУРСАЧ](https://github.com/babkaAnna/friend-or-foe/assets/134600713/0213bd50-b8df-4825-ad8a-6e2b01ae433a)
Обновленная диаграмма последовательности!

**Comment by tv1go** [comment]
![image](https://github.com/babkaAnna/friend-or-foe/assets/134600713/85f0852c-c1c8-42dd-ada2-8710bde4b112)
Финальная диаграмма последовательности!!!!!!!!!!!!!!

**Comment by tv1go** [comment]
![111](https://github.com/babkaAnna/friend-or-foe/assets/134600713/9de5e2d3-8e9f-4a8a-97fe-89355b094d48)
