### ISSUE TITLE
Подобрать языки программирования в соответствии с системным ПО

### ISSUE THREAD

**Issue by babkaAnna** [babkaAnna/friend-or-foe#9]
Обосновать свой выбор

**Comment by Semyon2807** [comment]
Я выбрал язык программирования Python.

**Comment by babkaAnna** [comment]
А почему? В описание написано

**Comment by Semyon2807** [comment]
Для разработки нашего ПО требуется оптимальное управление библиотеками, простой синтаксис и быстрая скорость обработки алгоритмов. Всё это имеется в языке Python, который я взял за основу для разработки программы.
